# Generated by Django 6.0 on 2025-12-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(verbose_name='Endereço de Entrega')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Rastreio')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transação')),
                ('shipping_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Envio')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo de Frete')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
    ]
