# Generated by Django 6.0 on 2025-12-28 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix (BRL)'), ('BTC', 'Bitcoin (Mainnet)'), ('LBTC', 'Liquid Bitcoin (Sidechain)'), ('DEPIX', 'DePix (Liquid Token)')], max_length=10)),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_crypto', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.order')),
            ],
        ),
    ]
