# Generated by Django manually

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, help_text='Preço de custo unitário', max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('link_compra', models.URLField(blank=True, help_text='Link do fornecedor (AliExpress, etc)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Qtd usada neste produto')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.componente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='componentes',
            field=models.ManyToManyField(through='core.Receita', to='core.componente'),
        ),
    ]